### ISSUE TITLE
MCGLM could accept numpy arrays directly (compatibility with statsmodels)

### ISSUE THREAD

**Issue by Spaak** [jeancmaia/mcglm#10]
Reviewing for JOSS, https://github.com/openjournals/joss-reviews/issues/6037

You emphasize in the paper/documentation that MCGLM inherits API standards from statsmodels. However, MCGLM requires y/X input to be wrapped as pandas DataFrames, whereas statsmodels accepts both those but also numpy arrays directly. I would recommend accepting numpy arrays to maintain API compatibility with statsmodels. (Note also mc_id etc should then accept arrays, rather than only dataframes.)

**Comment by Spaak** [comment]
I now see that the API docs specify `array_like` as input for endog/exog, so by docs they should accept numpy. However, this results in an error.

**Comment by jeancmaia** [comment]
Nice catch! I have tweaked the code, and you have in the version '0.2.4' a library reliable for both pandas and array inputs. Can you check it out again? 

Thank you for the great feedback.
